apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-pv0w
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-pv0w@sha256:37f7c294da199f44bd37cb1dbf03fa9ef29aafe450fa24b6c0e6d627e24fabb8
        name: my-nodejs
        resources: {}
status: {}
