apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-lne4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-lne4@sha256:100a5d950b636b2dc6729c0ffd6f80abfae1893fdb5b58b33781c7c3a1bbfd66
        name: my-python
        resources: {}
status: {}
